### ISSUE TITLE
provide an example with usage

### ISSUE THREAD

**Issue by mustafaskyer** [crabbynguyen/RN-Payfort-SDK#1]
thanks @crabbynguyen  for your great work,
i am a bit newbie with **PAYFORT**,
so i hope you can provide an example with usage,
thanks in advance

**Comment by crabbynguyen** [comment]
Hi @mustafaskir , I'm really sorry for my late response. I have updated the document with example.

**Comment by mustafaskyer** [comment]
great, thanks @crabbynguyen 
I'll check and give you a feedback
