### ISSUE TITLE
IOS app rejection due to Deprecated API Usage 

### ISSUE THREAD

**Issue by ank26oct** [crabbynguyen/RN-Payfort-SDK#7]
Dear Developer,

We identified one or more issues with a recent delivery for your app, "project" 1.8 (2.0). Please correct the following issues, then upload again.

ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).

Best regards,

The App Store Team

**Comment by ank26oct** [comment]
Resolved by using latest payfort IOS sdk 2.3

**Comment by MahmoudElmoghazy** [comment]
@ank26oct i can't find this version any where do you have any link

**Comment by UsamaAltaf** [comment]
@MahmoudElmoghazy did you solve the issue?

**Comment by RahulRijhwani** [comment]
> Resolved by using latest payfort IOS sdk 2.3

i can't find this version any where do you have any link or documents???

Awaiting for your response.
